### ISSUE TITLE
Looking for new owner

### ISSUE THREAD

**Issue by haydenbleasel** [haydenbleasel/gulp-jimp#11]
@antoinejaussoin @jolidog @iamstarkov @bensmithett @Everlag @arantes555?

**Comment by haydenbleasel** [comment]
@mattidupre @valentinvichnal @chteuchteu?

**Comment by iamstarkov** [comment]
@seamus-oconnor im sorry, man. was burnt out and missed this issue. i cant contribute, but nevertheless came here to say thanks to you for your time and work spent on this project

**Comment by chteuchteu** [comment]
Sorry - I missed the notification too. Plus, I don't use gulp anymore so :confused:
