### ISSUE TITLE
modifiers "bleed" with unexpected results

### ISSUE THREAD

**Issue by mshick** [haydenbleasel/gulp-jimp#7]
I noticed that if I attempt to create two modified versions of an image the modifications compound. For instance, the following code would give me two gray images.

```
gulp.src("mypic.png")
  .pipe(jimp({
    "-grey": { greyscale: true, resize: { width: 200 } },
    "-notgrey": { resize: { width: 200 } }
  });
```

**Comment by haydenbleasel** [comment]
Fixed in #8!
